#!/bin/bash

function renamefiles() {
	if [ $# -eq 2 ]; then
		cmd="find . -name $1"
		filesToRename="$(eval $cmd)"
		if [ "$filesToRename" == "" ]; then
			echo "No files found to rename"
			exit 1
		fi
		echo "$filestorename" | \
			while read line; do
				replacementPath="$(eval dirname $line)"
				replacementPath+="/$2"
				cmd="mv $line $replacementPath"
				eval "$cmd"
			done
	else
		cat >&2 <<EOF

usage: $(basename $0) original_file_name new_file_name
Find every file with the the given original file name in
this directory and all subdirectories and rename the file
with the given new file name.

EOF
	fi
}

renamefiles $@
